spring:
  application:
    name: atlas-auth
  config:
    import: optional:nacos:atlas-auth-dev.yaml
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:atlas-dev}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
        shared-configs:
          - data-id: atlas-common.yaml
            group: COMMON_GROUP
            refresh: true
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:atlas-dev}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

# Nacos 不可用时兜底
server:
  port: 8084
  servlet:
    context-path: /atlas-auth

