spring:
  application:
    name: atlas-gateway
  config:
    import: optional:nacos:atlas-gateway-dev.yaml
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yaml
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:dev}
        data-id: ${spring.application.name}-${spring.profiles.active:dev}.yaml
        refresh-enabled: true
        shared-configs:
          - data-id: atlas-gateway-${spring.profiles.active:dev}.yaml
            group: ${NACOS_GROUP:DEFAULT_GROUP}
            refresh: true
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:dev}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

# Nacos 不可用时兜底，避免启动失败
server:
  port: 8080
